image: ruby:2.3

cache:
  paths:
  - vendor

pages:
  script:
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - bundle install --path vendor
  - bundle exec middleman build
  artifacts:
    paths:
    - build
  only:
  - master
